### ISSUE TITLE
s390x and arm failures git/curl not found

### ISSUE THREAD

**Issue by nigelhorne** [FGasper/perl-github-action-tips#3]
It's a simple fix, you need to install git, curl and make thus:

`        run: docker run --rm --interactive s390x/ubuntu bash -c "apt update; apt dist-upgrade; apt -y install git curl build-essential; git clone --recurse-submodules $GITHUB_SERVER_URL/$GITHUB_REPOSITORY; cd $( echo $GITHUB_REPOSITORY | cut -d/ -f2 ); curl -L https://cpanmin.us | perl - --notest --installdeps .; perl Makefile.PL; make; prove -wlvmb t"`

**Comment by FGasper** [comment]
@nigelhorne Why `dist-upgrade`?

I think `apt update; apt install -y git cpanminus make` would do it … ?

**Comment by nigelhorne** [comment]
Yes it should.  Certainly feel free to use upgrade.  You may need to ensure you have 'curl' unless something else pulls it, I haven't checked that.

**Comment by FGasper** [comment]
Fixed w/ the latest update. Thanks!
