### ISSUE TITLE
Cygwin failures

### ISSUE THREAD

**Issue by nigelhorne** [FGasper/perl-github-action-tips#4]
I'm having problems with the cygwin code in the "Set up Cygwin" stage.  Any thoughts?  Here's what I'm seeing:

`Chocolatey v1.2.0
Upgrading the following packages:
cygwin
By upgrading, you accept licenses for the packages.
cygwin is not installed. Installing...

Cygwin v3.3.6 [Approved]
cygwin package files upgrade completed. Performing other installation steps.
Download site: http://mirrors.kernel.org/sourceware/cygwin/
Installing [64](https://github.com/nigelhorne/CGI-Info/actions/runs/3423054091/jobs/5701206590#step:2:68)-bit Cygwin...
Cygwin has been installed.
Added C:\ProgramData\chocolatey\bin\Cygwin.exe shim pointed to 'c:\tools\cygwin\cygwin.bat'.
Copying cygwin package manager (setup) to C:\tools\cygwin
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The upgrade of cygwin was successful.
  Software installed to 'C:\tools\cygwin'

Chocolatey upgraded 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Chocolatey v1.2.0

cabal has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.
Installing the following packages:
perl_base;perl-ExtUtils-MakeMaker;make;gcc-g++;libcrypt-devel;libnsl-devel;bash
By installing, you accept licenses for the packages.

Chocolatey installed 0/0 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
The system cannot find the file specified
Error: Process completed with exit code 1.`

**Comment by FGasper** [comment]
Everyone’s seeing that, I think: https://github.com/egor-tensin/setup-cygwin/issues/9
