### ISSUE TITLE
Build failures with Alpine Linux

### ISSUE THREAD

**Issue by nigelhorne** [FGasper/perl-github-action-tips#5]
I thought I'd give Alpine Linux testing a go but I'm unable to get it to work, this is what I'm seeing at the install dependencies stage, any idea?

Run apk add perl-app-cpanminus
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/3) Installing libbz2 (1.0.8-r1)
(2/3) Installing perl (5.34.1-r0)
(3/3) Installing perl-app-cpanminus (1.[7](https://github.com/nigelhorne/CGI-Info/actions/runs/3425094256/jobs/5705518428#step:3:8)046-r0)
Executing busybox-1.35.0-r17.trigger
OK: 44 MiB in 17 packages
cpanm (App::cpanminus) 1.7046 on perl 5.034001 built for x[8](https://github.com/nigelhorne/CGI-Info/actions/runs/3425094256/jobs/5705518428#step:3:9)6_64-linux-thread-multi
Work directory is /github/home/.cpanm/work/1667[9](https://github.com/nigelhorne/CGI-Info/actions/runs/3425094256/jobs/5705518428#step:3:10)65380.[16](https://github.com/nigelhorne/CGI-Info/actions/runs/3425094256/jobs/5705518428#step:3:17)
You have /usr/bin/wget
You have /bin/tar: tar (busybox) 1.35.0
You have /usr/bin/unzip
Entering /__w/CGI-Info/CGI-Info
--> Working on .
Configuring /__w/CGI-Info/CGI-Info ... N/A
! Configuring . failed. See /github/home/.cpanm/work/1667965380.16/build.log for details.
Error: Process completed with exit code 1.

**Comment by FGasper** [comment]
@nigelhorne Try adding `--verbose` to the `cpanm` invocation.

**Comment by nigelhorne** [comment]
I'm already using -v, isn't that the same?

**Comment by FGasper** [comment]
It should be.

You could alternatively try putting something like `find ~ -name build.log | xargs cat` after the cpanm invocation. You’ll need to adjust the command so that it tolerates cpanm failure rather than aborting.

I’m going to enable GitHub Discussions for this repo; feel free to post there if you have further usage questions.

Thanks!
